### ISSUE TITLE
Przewodnik po Netflix Stack

### ISSUE THREAD

**Issue by kgruszowski** [MeetHelp/backlog#75]
@koikos prośba do Ciebie o zestawienie w jedym miejscu jak odpalić całą architekture i jak tego używać?

**Comment by koikos** [comment]
Vide: https://github.com/MeetHelp/meethelp/blob/master/README.md

**Comment by koikos** [comment]
Dodałem także linka na głównej stronie projektu: https://meethelp.github.io/
